# Generated by Django 4.2.6 on 2023-10-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=200, unique=True, verbose_name='liste course name')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleName', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'article")),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=2000, verbose_name='desciption')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.shop')),
            ],
        ),
    ]
